### ISSUE TITLE
Error building the software with --noconfirm on manjaro

### ISSUE THREAD

**Issue by qwertyyuiopas** [rindeal/libfprint-vfs_proprietary-driver#14]
1 aur/libfprint-vfs_proprietary-git 0.99.0-3 (9) (0.00)
    libfprint with support for the Validity/VFS proprietary driver
==> Enter n° of packages to be installed (e.g., 1 2 3 or 1-3)
==> ---------------------------------------------------------
==> 1

==> Downloading libfprint-vfs_proprietary-git PKGBUILD from AUR...
x .SRCINFO
x .gitignore
x PKGBUILD
x build-vfs_proprietary.patch
 

 

 

 

 

libfprint-vfs_proprietary-git 0.99.0-3  (2020-08-28 12:02)
This package is orphaned
( Unsupported package: Potentially dangerous ! )
==> libfprint-vfs_proprietary-git dependencies:
 - libusb (already installed)
 - nss (already installed)
 - pixman (already installed)
 - glib2 (already installed)
 - git (already installed) [makedepend]
 - meson (already installed) [makedepend]
 - gtk-doc (already installed) [makedepend]
 - vfs495-daemon (building from AUR) [makedepend]
 - vfs495-daemon (building from AUR) [makedepend]

==> libfprint-vfs_proprietary-git conflicts:
 - libfprint-1.94.5-1

==> Continue building libfprint-vfs_proprietary-git ? [Y/n]
==> -------------------------------------------------------
==> 
==> Building and installing package
==> Install or build missing dependencies for libfprint-vfs_proprietary-git:
[sudo] password for unkown9: 
error: target not found: vfs495-daemon
==> Restart building libfprint-vfs_proprietary-git ? [y/N]
==> ------------------------------------------------------
==> %

**Comment by rindeal** [comment]
I do not maintain any of those AUR packages
