### ISSUE TITLE
How to install it on Fedora 29?

### ISSUE THREAD

**Issue by Bohooslav** [rindeal/libfprint-vfs_proprietary-driver#5]
I have `Bus 001 Device 003: ID 138a:003d Validity Sensors, Inc. VFS491` and Fedora Workstation on it. I try some but I can't install `insserv` that is required. Can you help me?

**Comment by rindeal** [comment]
I don't know what `insserv` is, how did you come up with that? Installation is not trivial, you need to patch, self-compile and replace a system library. If you haven't done such things yet there isn't much I can do for you.

**Comment by Bohooslav** [comment]
I try install that proprietary binaries https://github.com/rindeal/libfprint-vfs_proprietary-driver#proprietary-binaries but I got this problem
```
[b@l SP84530]$ sudo rpm -ivh Validity-Sensor-Setup-4.5-136.0.x86_64.rpm
warning: Validity-Sensor-Setup-4.5-136.0.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 1c774eaa: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
	package SynapticsIncorporated-4.5-136.0.x86_64 is already installed
	file /usr/bin/vcsFPService from install of SynapticsIncorporated-4.5-136.0.x86_64 conflicts with file from package Validity-Sensor-Setup-4.5-118.00.x86_64
	file /usr/lib/libvfsFprintWrapper.so from install of SynapticsIncorporated-4.5-136.0.x86_64 conflicts with file from package Validity-Sensor-Setup-4.5-118.00.x86_64
	file /usr/lib64/libvfsFprintWrapper.so from install of SynapticsIncorporated-4.5-136.0.x86_64 conflicts with file from package Validity-Sensor-Setup-4.5-118.00.x86_64
	file /usr/sbin/validity-sensor from install of SynapticsIncorporated-4.5-136.0.x86_64 conflicts with file from package Validity-Sensor-Setup-4.5-118.00.x86_64```
```
and with `--force`

```
[b@l SP84530]$ sudo rpm -ivh Validity-Sensor-Setup-4.5-136.0.x86_64.rpm --force
[sudo] password for b: 
warning: Validity-Sensor-Setup-4.5-136.0.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 1c774eaa: NOKEY<br> 
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:SynapticsIncorporated-4.5-136.0  ################################# [100%]
/var/tmp/rpm-tmp.FP9Ot0: line 2: sbin/insserv: No such file or directory
```

Honestly I am new in all this and do it in first time and do not know clearly from what begin and how to  compile it. Can you at least something recommend me?

**Comment by rindeal** [comment]
You're not supposed to install the RPM, but unpack and extract only the required binaries instead. You see it's just not trivial.

I suggest you to ask a maintainer of some 3rd party Fedora package repository to create a package for this.

If you want to experiment yourself anyway I can just point you to [this script](https://github.com/rindeal/libfprint-vfs_proprietary-driver/blob/master/.ci/script), which coincidentally builds this library on Fedora so you could just run it and it should download, unpack, patch and build the library (not install it though).
