### ISSUE TITLE
Ubuntu install

### ISSUE THREAD

**Issue by devyte** [rindeal/libfprint-vfs_proprietary-driver#6]
Hello,

I have an HP EliteBook 8460p, which has the vfs471 sensor.. After mucking around looking for linux support, I eventually came across the "ancient source floating around" which you referenced, then fprint, and then your repo here, which seems to be the most up to date working version of a driver.
Unfortunately, I'm not on Arch or similar, but rather on Ubuntu 18.04. I'm wondering if you could provide some guidance for building and installing this? I'm not quite sure where to even start, your install instructions seem rather alien to me.

**Comment by devyte** [comment]
To be clear, I already built everything using the [ci script](https://github.com/rindeal/libfprint-vfs_proprietary-driver/blob/master/.ci/script) as a guide: I installed the equivalent libs for Ubuntu, instead of using yum, then I followed the other steps in the script manually. It seemed to work, but I don't know what to do with the result of the build, mostly because I don't understand it.

**Comment by rindeal** [comment]
`vcsFPService` must be running and have RW access to the USB device representing the fingerprint reader, it also has to have RW access to `/tmp`.

`libfprint.so*` must be somewhere the dynamic linker of the app, you're trying to use the fingerprint sensor with, can find it (`/usr/lib64/` on my system).

`libvfsFprintWrapper.so` must be somewhere the build system and later the dynamic linker of `vfs_proprietary-capture-helper` can find it, `/opt/validity-sensor/usr/lib64/` by default, `/usr/lib64/` should work as well.

`vfs_proprietary-capture-helper` has to be under `/usr/libexec/libfprint/` by default and the user running the fingerprint reading app must have RX permissions to it. `vfs_proprietary-capture-helper` also must share RW access to the same `/tmp` directory as `vcsFPService` uses.

**Comment by perceival** [comment]
> To be clear, I already built everything using the [ci script](https://github.com/rindeal/libfprint-vfs_proprietary-driver/blob/master/.ci/script) as a guide: I installed the equivalent libs for Ubuntu, instead of using yum, then I followed the other steps in the script manually. It seemed to work, but I don't know what to do with the result of the build, mostly because I don't understand it.

Were you able to find solution to the following meson error?
vfs_proprietary/meson.build:1:11: ERROR: Unknown variable "drivers".
