### ISSUE TITLE
Is it possible to port to Debian?

### ISSUE THREAD

**Issue by switchy** [rindeal/libfprint-vfs_proprietary-driver#7]
I have very little functionality for my Debian.
Laptop: HP Elitbook 8460p
Device: Bus 001 Device 003: ID 138a:003c Validity Sensors, Inc. VFS471 Fingerprint Reader

**Comment by devyte** [comment]
Same boat. 
... I mean laptop.

**Comment by rindeal** [comment]
Everything is possible, if you have the right people to do it. As of now it seems that no one has stepped up for this job.
